### ISSUE TITLE
Add the proper exiplicit process of installing  and setting up the project locally in readme.md  

### ISSUE THREAD

**Issue by 7saikat7** [amanjha8100/AMS#2]
1. Start from forking the repo and cloning the dev branch 
2. Add all the steps, commands to set up the project locally.
3. Upload or add images if required 
4. Maintain a proper structure, don't delete any elements of the old readme.md file , add and modify if required

**Comment by Varun270** [comment]
@7saikat7 I would like to work on this issue. Kindly assign it to me!!

**Comment by 7saikat7** [comment]
Go ahead! 
*Note - create PR in dev branch only

**Comment by 7saikat7** [comment]
it's been long, please make the pr or else will I have to unassign u

**Comment by Varun270** [comment]
> it's been long, please make the pr or else will I have to unassign u

I have done the changes and also you have merged the PR, what else?

**Comment by pranavi79** [comment]
Is this still open?
