### ISSUE TITLE
Change In UI of HomePage

### ISSUE THREAD

**Issue by 7saikat7** [amanjha8100/AMS#3]
The whole website's UI will be changed, so provide some best modern design alternatives for the whole website, keeping in mind the user experience.
As of now , apply the design in the **_home page only_**, and if possible provide some design alternatives.

**Comment by ritikalohia** [comment]
Can you assign the respective task. I have some doubt also. Now, after running the project, we will see a table. We have to make a new home page, which sections are required in the home page?

**Comment by 7saikat7** [comment]
go ahead!

**Comment by 7saikat7** [comment]
any updates?

**Comment by pranavi79** [comment]
is this issue still open?

**Comment by 7saikat7** [comment]
yes

**Comment by pranavi79** [comment]
Can I be assigned to this issue then, please?

**Comment by 7saikat7** [comment]
go ahead! and if you have any doubt please let us know on discord. Also, asking you are participating from swoc21 right ?

**Comment by pranavi79** [comment]
Yes,I am
