### ISSUE TITLE
Add Custom User Model in Djnago

### ISSUE THREAD

**Issue by 7saikat7** [amanjha8100/AMS#4]
Add a custom user model in Django  which will consist of 
1. Principle [superuser access]
2.Hod[staff status]
3.Teacher[staff status ]
4. Students[normal users, is_active status only ]

**Comment by erbaibhav** [comment]
@7saikat7 @amanjha8100 do hod , teacher and student register from homepage in this feature??
and princinple user id will be created from admin side??

**Comment by 7saikat7** [comment]
no, do like that, use checkboxes is_hod, Is_principle and there will be different signup pages for them but will create it in a different issue, as of now make a custom user model , which will be used for basic login and signup

**Comment by 7saikat7** [comment]
would you like to work on it ?

**Comment by erbaibhav** [comment]
Sorry @7saikat7 due to college reopening i am busy a bit...you can assign this to anyone else...i will take another when i got free as soon....
Thanks:)

**Comment by shreyjha2309** [comment]
I'll try this one

**Comment by 7saikat7** [comment]
you will learn a lot from this issue !

**Comment by 7saikat7** [comment]
any updates ?

**Comment by Srishti-Ahuja** [comment]
If no one is working on this issue, I would like to take it up

**Comment by 7saikat7** [comment]
ya sure, please try to do it quickly.
