### ISSUE TITLE
Robust model is required for  attendance 

### ISSUE THREAD

**Issue by 7saikat7** [amanjha8100/AMS#5]
Add fields like subject,date,topic ,date_model_created in models.py for more structural and robust model

**Comment by saisumanthkumar** [comment]
@7saikat7 I would like to work on this

**Comment by 7saikat7** [comment]
ok go for it,
Estimate Deadline 16/11/21
**Note -Create PR only in Dev branch

**Comment by 7saikat7** [comment]
any updates @saisumanthkumar ?

**Comment by saisumanthkumar** [comment]
@7saikat7 yeah will submit by today evening

**Comment by 7saikat7** [comment]
any updates?

**Comment by 7saikat7** [comment]
is there any problem? or if you are not working I have to unassign you so that others can pick up this.

**Comment by prateekmohanty63** [comment]
Hello I am intrested in taking up this issue
Can you please give a bit more claity on the changes that needs to be done

**Comment by 7saikat7** [comment]
fields like subject,date,topic ,date_model_created are needed think about a class attendance and u can add parameters,required to improve the model
